name: 'Zip template'
on:
  push:
    paths:
      - 'templates/**'
    branches:
      - main

jobs:
  Templates:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install Zip
        run: sudo apt-get install zip unzip

      - name: Zip commit
        run: |
          changed_files=$(git diff --name-only  ${{ github.sha }} HEAD)

          echo "changed files in the commit, ${changed_files}"
          templates_arr=()
          echo "$changed_files" | sed 's/\/[^\/]*$//' | grep '^templates/' | sort -u > temp.txt
          mapfile -t templates_arr < temp.txt

          for template in "${templates_arr[@]}"; do
            name="${template##/ }.zip"
            zip $name $template
          done
