name: 'Zip template'
on:
  push:
    paths:
      - 'templates/**'
    branches:
      - main

jobs:
  Templates:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install Zip
        run: sudo apt-get install zip unzip

      - name: Zip commit
        run: |
          temparr=${{ github.event.commits }}
          changed_files=$(git show --name-only --pretty="" ${{ github.sha }})

          for x in in "${temparr[@]}"; do
            echo "$x"
          done

          echo "changed files in the commit, ${changed_files}"
          templates_arr=()
          echo "$changed_files" | sed 's/\/[^\/]*$//' | grep '^templates/' | sort -u > temp.txt
          mapfile -t templates_arr < temp.txt

          for template in "${templates_arr[@]}"; do
            name="${template##/ }.zip"
            zip $name $template
          done
