name: 'Zip template'
on:
  push:
    paths:
      - 'templates/**'
    branches:
      - main

jobs:
  Templates:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install Zip
        run: sudo apt-get install zip unzip

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Zip commit
        run: |
          node scripts/zip.js
          run: node script.js
        env:
          GITHUB_PUSH_OBJECT: ${{ github.event }}
